import {
  Sprint,
  LandingPage,
  AiIntegration,
  Performance,
  UiUxDesign,
  Integration,
  Debug,
  Consulting,
  WebDevelopment,
  Ecommerce,
  MobileApp,
  Search,
  PenTool,
  Code,
  Rocket,
  Brain,
} from "./index";

export const serviceIcons = {
  sprint: Sprint,
  "landing-page": LandingPage,
  "ai-integration": AiIntegration,
  "ai-consulting": AiIntegration,
  performance: Performance,
  "ui-ux-design": UiUxDesign,
  integration: Integration,
  debug: Debug,
  consulting: Consulting,
  "web-development": WebDevelopment,
  ecommerce: Ecommerce,
  "mobile-app": MobileApp,
  search: Search,
  "pen-tool": PenTool,
  code: Code,
  rocket: Rocket,
  brain: Brain,
};
