/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '1.5rem',
        lg: '2rem',
        xl: '2.5rem',
        '2xl': '3rem',
      },
    },
    extend: {
      colors: {
        // Brand palettes via CSS variables (works at runtime and supports theming)
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
        },
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          950: 'var(--color-secondary-950)',
        },
        text: {
          DEFAULT: 'var(--color-text)',
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          headings: 'var(--color-text-headings)',
          link: 'var(--color-text-link)',
          linkHover: 'var(--color-text-link-hover)',
        },
        background: {
          DEFAULT: 'var(--color-background)',
          muted: 'var(--color-background-muted)',
        },
        surface: { DEFAULT: 'var(--color-surface)' },
        border: { DEFAULT: 'var(--color-border)' },
        on: {
          primary: 'var(--color-on-primary)',
          secondary: 'var(--color-on-secondary)',
          surface: 'var(--color-on-surface)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        'fluid-xs': 'clamp(0.75rem, 0.5vw + 0.65rem, 0.875rem)',
        'fluid-sm': 'clamp(0.875rem, 0.5vw + 0.775rem, 1rem)',
        'fluid-base': 'clamp(1rem, 1vw + 0.75rem, 1.125rem)',
        'fluid-lg': 'clamp(1.125rem, 1vw + 0.875rem, 1.25rem)',
        'fluid-xl': 'clamp(1.25rem, 1.5vw + 0.9rem, 1.5rem)',
        'fluid-2xl': 'clamp(1.5rem, 2vw + 1rem, 2rem)',
        'fluid-3xl': 'clamp(1.875rem, 2.5vw + 1.2rem, 2.5rem)',
        'fluid-4xl': 'clamp(2.25rem, 3.5vw + 1.5rem, 3.5rem)',
        'fluid-5xl': 'clamp(3rem, 5vw + 2rem, 4.5rem)',
      },
      spacing: {
        'section-xs': 'var(--space-8)',
        'section-sm': 'var(--space-12)',
        'section-md': 'var(--space-16)',
        'section-lg': 'var(--space-20)',
        'section-xl': 'var(--space-24)',
        'section-2xl': 'var(--space-32)',
      },
      zIndex: { 10: '10', 20: '20', 30: '30', 40: '40', 50: '50' },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/container-queries'),
  ],
};
