import { test, expect } from '@playwright/test';

/**
 * NosytLabs Comprehensive UI Tests
 * Generated by MCP Playwright Testing System
 * 
 * Tests cover:
 * - Navigation functionality
 * - Responsive design
 * - Cross-browser compatibility
 * - Accessibility features
 * - Performance validation
 * - Terminal interface functionality
 */

test.describe('NosytLabs Website - Comprehensive UI Testing', () => {
  
  test.beforeEach(async ({ page }) => {
    // Navigate to homepage before each test
    await page.goto('https://nosytlabs.com');
    await page.waitForLoadState('networkidle');
  });

  test('Homepage - Verify terminal interface and basic layout', async ({ page }) => {
    // Verify page title
    await expect(page).toHaveTitle(/Nosyt Labs - Notable Opportunities Shape Your Tomorrow/);
    
    // Verify terminal interface elements
    await expect(page.locator('text=ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL')).toBeVisible();
    await expect(page.locator('text=NOSYT LABS SECURE TERMINAL')).toBeVisible();
    
    // Verify navigation is present
    await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible();
    
    // Verify footer elements
    await expect(page.locator('text=© 2025 Nosyt Labs')).toBeVisible();
    
    // Take screenshot for visual regression
    await page.screenshot({ path: 'test-results/homepage-desktop.png', fullPage: true });
  });

  test('Navigation - Test all navigation links', async ({ page }) => {
    const navigationLinks = [
      { name: 'Home', url: '/' },
      { name: 'Projects', url: '/projects' },
      { name: 'Blog', url: '/blog' },
      { name: 'Vault Shelter', url: '/vault-shelter' },
      { name: 'Contact', url: '/contact' }
    ];

    for (const link of navigationLinks) {
      // Click navigation link
      await page.getByRole('link', { name: link.name }).click();
      
      // Verify URL
      await expect(page).toHaveURL(new RegExp(link.url));
      
      // Verify page loads properly
      await expect(page.locator('text=ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL')).toBeVisible();
      
      // Take screenshot
      await page.screenshot({ 
        path: `test-results/${link.name.toLowerCase().replace(' ', '-')}-page.png`,
        fullPage: true 
      });
    }
  });

  test('Responsive Design - Mobile viewport testing', async ({ page }) => {
    // Test mobile viewport (iPhone 12)
    await page.setViewportSize({ width: 390, height: 844 });
    
    // Verify mobile navigation
    const mobileMenuButton = page.getByRole('button', { name: 'Toggle navigation' });
    await expect(mobileMenuButton).toBeVisible();
    
    // Test mobile menu toggle
    await mobileMenuButton.click();
    
    // Verify terminal interface is responsive
    await expect(page.locator('text=ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL')).toBeVisible();
    
    // Take mobile screenshot
    await page.screenshot({ path: 'test-results/homepage-mobile.png', fullPage: true });
    
    // Test tablet viewport (iPad)
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.screenshot({ path: 'test-results/homepage-tablet.png', fullPage: true });
  });

  test('Accessibility - Verify accessibility features', async ({ page }) => {
    // Check for skip link
    await expect(page.getByRole('link', { name: 'Skip to main content' })).toBeVisible();
    
    // Verify main landmark
    await expect(page.getByRole('main')).toBeVisible();
    
    // Verify navigation landmark
    await expect(page.getByRole('navigation')).toBeVisible();
    
    // Test keyboard navigation
    await page.keyboard.press('Tab');
    await page.keyboard.press('Tab');
    
    // Verify focus is visible (this would need custom focus styles)
    const focusedElement = page.locator(':focus');
    await expect(focusedElement).toBeVisible();
  });

  test('Performance - Page load and Core Web Vitals', async ({ page }) => {
    // Measure page load time
    const startTime = Date.now();
    await page.goto('https://nosytlabs.com');
    await page.waitForLoadState('networkidle');
    const loadTime = Date.now() - startTime;
    
    // Verify reasonable load time (under 3 seconds)
    expect(loadTime).toBeLessThan(3000);
    
    // Check for performance metrics
    const performanceMetrics = await page.evaluate(() => {
      const navigation = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;
      return {
        domContentLoaded: navigation.domContentLoadedEventEnd - navigation.domContentLoadedEventStart,
        loadComplete: navigation.loadEventEnd - navigation.loadEventStart,
        firstByte: navigation.responseStart - navigation.requestStart
      };
    });
    
    // Verify performance thresholds
    expect(performanceMetrics.firstByte).toBeLessThan(1000); // TTFB under 1s
    expect(performanceMetrics.domContentLoaded).toBeLessThan(2000); // DCL under 2s
  });

  test('Theme Toggle - Test theme switching functionality', async ({ page }) => {
    // Look for theme toggle button
    const themeToggle = page.getByRole('button', { name: 'Toggle theme' });
    
    if (await themeToggle.isVisible()) {
      // Test theme toggle
      await themeToggle.click();
      
      // Wait for theme change
      await page.waitForTimeout(500);
      
      // Take screenshot of alternate theme
      await page.screenshot({ path: 'test-results/homepage-alt-theme.png', fullPage: true });
      
      // Toggle back
      await themeToggle.click();
      await page.waitForTimeout(500);
    }
  });

  test('Terminal Interface - Test command functionality', async ({ page }) => {
    // Look for terminal input
    const terminalInput = page.locator('input[type="text"], textbox');
    
    if (await terminalInput.isVisible()) {
      // Test terminal commands
      await terminalInput.fill('help');
      await page.keyboard.press('Enter');
      
      // Wait for response
      await page.waitForTimeout(1000);
      
      // Test other commands
      await terminalInput.fill('ls');
      await page.keyboard.press('Enter');
      await page.waitForTimeout(1000);
      
      // Take screenshot of terminal interaction
      await page.screenshot({ path: 'test-results/terminal-interaction.png', fullPage: true });
    }
  });

  test('Cross-browser Compatibility - Browser-specific tests', async ({ page, browserName }) => {
    // Test browser-specific functionality
    console.log(`Testing on ${browserName}`);
    
    // Verify basic functionality works across browsers
    await expect(page.locator('text=ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL')).toBeVisible();
    
    // Test CSS Grid/Flexbox support
    const mainContent = page.getByRole('main');
    await expect(mainContent).toBeVisible();
    
    // Browser-specific screenshot
    await page.screenshot({ 
      path: `test-results/homepage-${browserName}.png`, 
      fullPage: true 
    });
  });

  test('Error Handling - Test 404 and error pages', async ({ page }) => {
    // Test 404 page
    const response = await page.goto('https://nosytlabs.com/nonexistent-page');
    
    // Verify 404 response or custom error page
    if (response?.status() === 404) {
      await expect(page.locator('text=404')).toBeVisible();
    }
    
    // Take screenshot of error page
    await page.screenshot({ path: 'test-results/404-page.png', fullPage: true });
  });

  test('SEO and Meta Tags - Verify meta information', async ({ page }) => {
    // Check meta description
    const metaDescription = page.locator('meta[name="description"]');
    await expect(metaDescription).toHaveAttribute('content', /.+/);
    
    // Check Open Graph tags
    const ogTitle = page.locator('meta[property="og:title"]');
    const ogDescription = page.locator('meta[property="og:description"]');
    
    if (await ogTitle.count() > 0) {
      await expect(ogTitle).toHaveAttribute('content', /.+/);
    }
    
    // Check canonical URL
    const canonical = page.locator('link[rel="canonical"]');
    if (await canonical.count() > 0) {
      await expect(canonical).toHaveAttribute('href', /.+/);
    }
  });

});

// Configuration for different browsers and devices
test.describe('Multi-Browser Testing', () => {
  ['chromium', 'firefox', 'webkit'].forEach(browserName => {
    test(`${browserName} - Basic functionality`, async ({ page }) => {
      await page.goto('https://nosytlabs.com');
      await expect(page.locator('text=ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL')).toBeVisible();
      await page.screenshot({ path: `test-results/cross-browser-${browserName}.png` });
    });
  });
});

// Mobile device testing
test.describe('Mobile Device Testing', () => {
  const devices = [
    { name: 'iPhone 12', width: 390, height: 844 },
    { name: 'iPad', width: 768, height: 1024 },
    { name: 'Samsung Galaxy S21', width: 360, height: 800 }
  ];

  devices.forEach(device => {
    test(`${device.name} - Responsive design`, async ({ page }) => {
      await page.setViewportSize({ width: device.width, height: device.height });
      await page.goto('https://nosytlabs.com');
      
      await expect(page.locator('text=ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL')).toBeVisible();
      await page.screenshot({ 
        path: `test-results/device-${device.name.toLowerCase().replace(' ', '-')}.png`,
        fullPage: true 
      });
    });
  });
});
