/**
 * Performance Optimization Utilities - Generated by Master Build Optimizer
 * Consolidated performance enhancements for NosytLabs website
 */

import type { PerformanceNavigationTimingExtended } from '@/types/performance';

// Lazy loading utility
export function setupLazyLoading() {
  if ('IntersectionObserver' in window) {
    const imageObserver = new IntersectionObserver((entries, observer) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          const img = entry.target as HTMLImageElement;
          const dataSrc = img.dataset.src;
          if (dataSrc) {
            img.src = dataSrc;
          }
          img.classList.remove('lazy');
          observer.unobserve(img);
        }
      });
    });

    document.querySelectorAll('img[data-src]').forEach(img => {
      imageObserver.observe(img);
    });
  }
}

// Critical resource preloading
export function preloadCriticalResources() {
  const criticalResources = [
    { href: '/styles/bundles/critical.css', as: 'style' },
    { href: '/scripts/bundles/core.min.js', as: 'script' }
  ];

  criticalResources.forEach(resource => {
    const link = document.createElement('link');
    link.rel = 'preload';
    link.href = resource.href;
    link.as = resource.as;
    document.head.appendChild(link);
  });
}

// Performance monitoring
export function monitorPerformance() {
  if ('performance' in window) {
    window.addEventListener('load', () => {
      setTimeout(() => {
        const perfData = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTimingExtended;
        if (perfData) {
          const metrics = {
            dns: perfData.domainLookupEnd - perfData.domainLookupStart,
            tcp: perfData.connectEnd - perfData.connectStart,
            ttfb: perfData.responseStart - perfData.requestStart,
            download: perfData.responseEnd - perfData.responseStart,
            dom: perfData.domContentLoadedEventEnd - perfData.domContentLoadedEventStart,
            load: perfData.loadEventEnd - perfData.loadEventStart
          };

          console.log('Performance Metrics:', metrics);
        }
      }, 0);
    });
  }
}

// Initialize all performance optimizations
export function initPerformanceOptimizations() {
  setupLazyLoading();
  preloadCriticalResources();
  monitorPerformance();
}